---
title: "Reading and Cleaning NOAA Weather Forecasts"
author: "Jaxon Stuhr"
date: "2022-12-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(here)
library(tidyverse)
library(mapview)
library(writexl)
library(stringr)
library(lubridate)
library(R.utils)
```

```{r}
# pandas already installed
# py_install("pandas")
pd = import("pandas")
```

```{r}
# pull weather pkl file names/paths into array
fc_weather_files <- list.files(path="C:/Users/jzs88/Box/LMP_Predictive_Modeling/fcWeather",
                    pattern=".pkl", 
                    all.files=T, 
                    full.names=T)

ac_lmp_files <- list.files(path="C:/Users/jzs88/Box/LMP_Predictive_Modeling/acLMPs",
                    pattern=".pkl", 
                    all.files=T, 
                    full.names=T)

us_land_path <- "C:/Users/jzs88/Box/LMP_Predictive_Modeling/spatial_grid/USland_0.125_(-125,-112)_(32,43).pkl"
ref_grid_path <- "C:/Users/jzs88/Box/LMP_Predictive_Modeling/spatial_grid/ref_grid_0.125_(-125,-112)_(32,43).pkl"
```

```{r}
# setup crosswalk of weather parameters
weather_params_fc = data.frame(
  param = c("PRES", "PRATE", "DSWRF", "DLWRF", "DPT_2m", "RH_2m", "TMP_2m", "WS_10m", "WS_60m", "WS_80m", "WS_100m", "WS_120m", "DI_2m", "WC_2m", "HCDH_2m", "GSI"),
  unit = c("pa", "kg/m2/s", "W/m2", "W/m2", "K", "%", "K", "m/s", "m/s", "m/s", "m/s", "m/s", "?", "K?", "degree_hour", "?")
)
```

```{r}
# read in us_land and ref_grid from pkl files
us_land = pd$read_pickle(us_land_path)
ref_grid = pd$read_pickle(ref_grid_path)

# convert entire grid to data frame
ref_grid = as.data.frame(ref_grid) %>% 
  rename(lon = V1,
         lat = V2)

#initialize us grid
us_grid = ref_grid %>% 
  mutate(land = 0)

# label and filter for only points on land
us_grid$land[1:length(us_grid$land)] = us_land
us_grid = us_grid %>% 
  filter(land == 1)
```

```{r}
# read in a sample weather file, vectorize
#sample_weather = c(pd$read_pickle(ac_weather_files[1]))
hours = 36
params = 16
locs = 9152
# build list of parameters that is length 36 (hrs) x 16 (parameters)
hour = 0
param_index = 1
params_list = matrix(1, hours*params)
for (i in 1:length(params_list)) {
  if (hour < hours) {
    params_list[i] = weather_params_fc$param[param_index]
    hour = hour + 1
  } else {
    param_index = param_index + 1
    params_list[i] = weather_params_fc$param[param_index]
    hour = 1
  }
}
```

```{r}
# build lists of lats and lons that are length 36 (hrs) x 16 (parameters) x 9152 (locations)
hour_params = 0
loc_index = 1
lat_list = matrix(1, hours*params*locs)
lon_list = matrix(1, hours*params*locs)
for (i in 1:length(lat_list)) {
  if (hour_params < hours*params) {
    lat_list[i] = ref_grid$lat[loc_index]
    lon_list[i] = ref_grid$lon[loc_index]
    hour_params = hour_params + 1
  } else {
    loc_index = loc_index + 1
    lat_list[i] = ref_grid$lat[loc_index]
    lon_list[i] = ref_grid$lon[loc_index]
    hour_params = 1
  }
}
```

```{r}
# create function to build dataframe from list of files paths, list of dates, and variable lists
build_weather_data_frame = function(file_paths) {

  # initialize complete weathere data frame
  weather_data_frame = data.frame(matrix(nrow = 0, ncol = 137284))
  colnames(weather_data_frame) = c("value", "year", "month", "day", "hour", "parameter", "lat", "lon")
  
  # iterate through file paths provided
  for (i in 1:length(file_paths)) {
    print(i)
    flush.console()
    # read in vectorized weather data from current file path
    weather_list = c(pd$read_pickle(file_paths[i]))
    date = ymd(str_sub(sub("-00.pkl", "", file_paths[i]), -8, -1))
    date_list = ymd_h(paste(year(date), month(date), day(date), 16)) + hours(0:35)
    date_list[1:8] = ymd_h(paste(2000, 1, 1,1))
    date_list[33:36] = ymd_h(paste(2000, 1, 1,1))
    # build new data frame of current weather data
    current_weather = data.frame(
      # values from current vectorized weather list
      value = weather_list,
      fc_date = date,
      date = date_list,
      parameter = params_list,
      lat = lat_list, 
      lon = lon_list
      ) %>% 
      filter((lat %% .25) == 0) %>% 
      filter((lon %% .25) == 0) %>% 
      filter(date != ymd_h(paste(2000, 1, 1,1))) %>% 
      pivot_wider(names_from = c(parameter, lat, lon), values_from = value, names_sep = "//")
    # append current weather data to complete data frame
    weather_data_frame = rbind(weather_data_frame, current_weather)
  }
  
  # return data frame with weather from all files and dates provided
  return(weather_data_frame)
}
```

```{#kl;r}
# build weather data frame for first 80 actual weather data files, takes ~8 minutes, fails for 80+ files
weather_1 = build_weather_data_frame(fc_weather_files[1:50])
weather_2 = build_weather_data_frame(fc_weather_files[51:100])
weather_3 = build_weather_data_frame(fc_weather_files[101:106])
weather_4 = build_weather_data_frame(fc_weather_files[108:200])
weather_5 = build_weather_data_frame(fc_weather_files[201:250])
weather_6 = build_weather_data_frame(fc_weather_files[251:300])
weather_7 = build_weather_data_frame(fc_weather_files[301:365])
# bind weather data together
all_weather = rbind(weather_1, weather_2, weather_3, weather_4, weather_5, weather_6, weather_7)

saveRDS(all_weather, here("outputs", "fc_weather_1_365.rds"))

```

```{r}
all_weather_1 = readRDS(here("outputs", "fc_weather_1_365.rds"))
```

```{#r}
# build weather data frame for first 80 actual weather data files, takes ~8 minutes, fails for 80+ files
weather_1 = build_weather_data_frame(fc_weather_files[366:400])
weather_2 = build_weather_data_frame(fc_weather_files[401:450])
weather_3 = build_weather_data_frame(fc_weather_files[451:500])
weather_4 = build_weather_data_frame(fc_weather_files[501:550])
weather_5 = build_weather_data_frame(fc_weather_files[551:600])
weather_6 = build_weather_data_frame(fc_weather_files[601:650])
weather_7 = build_weather_data_frame(fc_weather_files[651:700])
weather_8 = build_weather_data_frame(fc_weather_files[701:730])


all_weather = rbind(weather_1, weather_2, weather_3, weather_4, weather_5, weather_6, weather_7, weather_8)

saveRDS(all_weather, here("outputs", "fc_weather_366_730.rds"))

```

```{r}
all_weather_2 = readRDS(here("outputs", "fc_weather_366_730.rds"))
```

```{#r}
# build weather data frame for first 80 actual weather data files, takes ~8 minutes, fails for 80+ files
weather_1 = build_weather_data_frame(fc_weather_files[731:800])
weather_2 = build_weather_data_frame(fc_weather_files[801:850])
weather_3 = build_weather_data_frame(fc_weather_files[851:900])
weather_4 = build_weather_data_frame(fc_weather_files[901:950])
weather_5 = build_weather_data_frame(fc_weather_files[951:1000])
weather_6 = build_weather_data_frame(fc_weather_files[1001:1050])
weather_7 = build_weather_data_frame(fc_weather_files[1051:1095])


all_weather = rbind(weather_1, weather_2, weather_3, weather_4, weather_5, weather_6, weather_7)

saveRDS(all_weather, here("outputs", "fc_weather_731_1095.rds"))

```

```{r}
all_weather_3 = readRDS(here("outputs", "fc_weather_731_1095.rds"))
```

```{#r}
# build weather data frame for first 80 actual weather data files, takes ~8 minutes, fails for 80+ files
weather_1 = build_weather_data_frame(fc_weather_files[1096:1150])
weather_2 = build_weather_data_frame(fc_weather_files[1151:1169])

all_weather = rbind(weather_1, weather_2)

saveRDS(all_weather, here("outputs", "fc_weather_1096_1169.rds"))

```

```{r}
all_weather_4 = readRDS(here("outputs", "fc_weather_1096_1169.rds"))
```

```{r}
all_weather = rbind(all_weather_1, all_weather_2, all_weather_3, all_weather_4)
```

```{r}
saveRDS(all_weather, here("outputs", "fc_all_weather_1169.rds"))
```


